[workspace]
members = [
    "blake2",
    "gost94",
    "groestl",
    "k12",
    "md2",
    "md4",
    "md5",
    "ripemd160",
    "ripemd320",
    "sha1",
    "sha2",
    "sha3",
    "shabal",
    "streebog",
    "whirlpool",
]

[patch.crates-io]
digest = { git = "https://github.com/RustCrypto/traits" }
block-buffer = { git = "https://github.com/RustCrypto/utils" }
crypto-mac = { git = "https://github.com/rustcrypto/traits" }
