[package]
name = "sha3"
version = "0.5.3"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "SHA-3 (Keccak) hash function"
documentation = "https://docs.rs/sha3"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "sha3", "keccak", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.5"
generic-array = "0.7"
byte-tools = "0.1"
digest-buffer = "0.3"

[dev-dependencies]
crypto-tests = "0.4"

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
