[package]
name = "whirlpool"
version = "0.8.1"
description = "Whirlpool hash function"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/whirlpool"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "whirlpool", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = { version = "0.9.0-pre", git = "https://github.com/RustCrypto/traits" }
block-buffer = { version = "0.7", git = "https://github.com/RustCrypto/utils" }
byte-tools = "0.3"
opaque-debug = "0.2"
whirlpool-asm = { version="0.5", optional=true }

[dev-dependencies]
digest = { version = "0.9.0-pre", features = ["dev"], git = "https://github.com/RustCrypto/traits" }
hex-literal = "0.1"

[features]
default = ["std"]
std = ["digest/std"]
asm = ["whirlpool-asm"]
