[package]
name = "sha-1"
version = "0.4.0"
authors = ["The RustCrypto Devs"]
license = "MIT/Apache-2.0"
description = "SHA-1 hash function"
documentation = "https://docs.rs/sha-1"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "sha1", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.6"
generic-array = "0.8"
byte-tools = "0.2"
block-buffer = "0.2"
fake-simd = "0.1"
sha1-asm = {version="0.3", optional=true}

[dev-dependencies]
crypto-tests = "0.5"

[features]
asm = ["sha1-asm"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
