[package]
name = "sha2"
version = "0.5.1"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "SHA-2 hash functions"
documentation = "https://docs.rs/sha2"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "sha2", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.5"
generic-array = "0.7"
byte-tools = "0.1"
digest-buffer = "0.3"
fake-simd = "0.1"

[dev-dependencies]
crypto-tests = "0.4"

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
