[package]
name = "sha2"
version = "0.4.1"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "SHA-2 hash functions"
#documentation = "https://docs.rs/sha1"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "sha2", "hash", "digest"]
categories = ["cryptography"]

[dependencies]
digest = "0.4"
digest-buffer = "0.2"
generic-array = "0.6"
byte-tools = "0.1"
fake-simd = "0.1"

[dev-dependencies]
crypto-tests = "0.3"

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
