[package]
name = "streebog"
version = "0.3.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "Streebog (GOST R 34.11-2012) hash function"
documentation = "https://docs.rs/streebog"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "streebog", "gost", "hash", "digest"]

[dependencies]
digest = "0.4"
digest-buffer = "0.2"
generic-array = "0.6"
byte-tools = "0.1"

[dev-dependencies]
crypto-tests = "0.3"
