[package]
name = "md-5"
version = "0.4.4"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "MD5 hash function"
documentation = "https://docs.rs/md-5"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "md5", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.5"
generic-array = "0.7"
byte-tools = "0.1"
digest-buffer = "0.3"
md5-asm = {version="0.2", optional=true}

[dev-dependencies]
crypto-tests = "0.4"

[features]
asm = ["md5-asm"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
