[package]
name = "ripemd160"
version = "0.5.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "RIPEMD-160 hash function"
documentation = "https://docs.rs/ripemd160"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "ripemd160", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.5.0-rc1"
generic-array = "0.7"
byte-tools = "0.1"
digest-buffer = "0.3.0-alpha"

[dev-dependencies]
crypto-tests = "0.4.0-alpha"

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
