[package]
name = "shabal"
version = "0.2.0"
description = "Shabal hash functions"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/shabal"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "shabal", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "= 0.9.0-pre"
block-buffer = "0.7"
opaque-debug = "0.2"

[dev-dependencies]
digest = { version = "= 0.9.0-pre", features = ["dev"] }
hex-literal = "0.1"

[features]
default = ["std"]
std = ["digest/std"]
