name: blake2

on:
  pull_request:
    paths:
      - "blake2/**"
      - "Cargo.*"
  push:
    branches: master
    paths:
      - "blake2/**"
      - "Cargo.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.41.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo build --no-default-features --release --target ${{ matrix.target }}
        working-directory: blake2
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.41.0 # MSRV
          - stable
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - run: cargo test --no-default-features
      working-directory: blake2
    - run: cargo test
      working-directory: blake2
  simd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: cargo test --features simd
        working-directory: blake2
      - run: cargo test --features simd_opt
        working-directory: blake2
      - run: cargo test --features simd_asm
        working-directory: blake2
